var GAME_LEVELS = [
  ["                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                      ggg                                  ",
   "                                                    ggggggg                                ",
   "                                                  ggggggggggg                              ",
   "x                                               ggggggggggggggg                           x",
   "x                                                g           g                            x",
   "x                                                g           g                            x",
   "x                                                                                         x",
   "x                 gg           gg                                   gg         gg         x",
   "x                gggg         gggg               g           g     gggg       gggg        x",
   "x                gggg    =    gggg    =          g      @    g     gggg       gggg        x",
   "x     r          gggg         gggg              ggggggggggggggg    gggg       gggg        x",
   "xxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxx                                                    xxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxx                                                    xxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxx                   b                              xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxx                                                  xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx                                                xxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx                                                xxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx                                              xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx                                              xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                                                        xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                                                        xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx                                  y       xxxxxxxxxx   xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx                                          xxxxxxxxxx   xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxx                                        xxxxxxxxxxx   xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxx                                        xxxxxxxxxxx   xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                      xxxxxxxxxxxx   xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                      xxxxxxxxxxxx   xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                    xxxxxxxxxxxxx   xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                    xxxxxxxxxxxxx!!!xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                  xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                  xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       =                 =      xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 v              xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "x                 gg           gg           gg            gg            gg                                       x",
   "x                gggg         gggg         gggg          gggg          gggg                                      x",
   "x                gggg    =    gggg    =    gggg     =    gggg          gggg         =                 =          x",
   "x    @           gggg         gggg         gggg          gggg          gggg                 r                    x",
   "xxxxxxxxxxxxxxx  xxxx  xxxxx  xxxx  xxxxx  xxxx  xxxxxx  xxxx  xxxxxx  xxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx      xxxxxxx      xxxxxxx      xxxxxxxx      xxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx      xx   xx      xx           xx    xx      xx    xx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx      xx   xx      xx           xx    xx      xx    xx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx    v xx   xx      xx           xx    xx      xx    xx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx  xxxx   xxxxxxxxxx    xxxxxxxxx    xxxxxxxxxx    xxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx                                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx                                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx                      gg                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx                     gggg                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx                     gggg                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx                     gggg                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx   gg           gg   xxxx    gg           gg            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx  gggg         gggg         gggg         gggg           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx  gggg    =    gggg    =    gggg    =    gggg           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxx  gggg         gggg       y gggg         gggg           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  "],   
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                     y                                                        ",
   "                                                    ggg                                                       ",
   "                                                  ggggggg                                                     ",
   "                                                ggggggggggg                                                   ",
   "                                    gg        ggggggggggggggg        gg                                       ",
   "                                   gggg        g           g        gggg                                      ",
   "                                   gggg        g           g        gggg                                      ",
   "                                   gggg                             gggg                                      ",
   "      gg           gg              xxxx                    b        xxxx      gg             gg               ",
   "     gggg         gggg                         g           g                 gggg           gggg              ",
   "     gggg         gggg     =                   g     @     g                 gggg           gggg              ",
   "     gggg         gggg          r  x          ggggggggggggggg                gggg           gggg              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx             xxxxxxxxxx       xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx             xxxxxx           xxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx             xxxxxx       xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx             xxx          xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx             xxx      xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx                      xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx     =       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxx         v   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
